
env = Environment(CCFLAGS='-O2',
				  LIBS=['boost_system', 'boost_iostreams', 'boost_filesystem', 'xerces-c'], 
				  LIBPATH=['/usr/local/lib'])

env.Program(program='rcsdropper', source=Glob('*.cpp'))
